#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_birthday:
    resource: App\Controller\BirthdayController
    type: annotation

# config/routes.yaml
api_login_check:
    path: /api/login_check

    # config/routes.yaml
user:
    path: '/api/users'
    controller: 'App\Controller\UserController::index'

user_create:
    path: '/api/users/new'
    controller: 'App\Controller\UserController::create'

user_show:
    path: '/api/users/{id}'
    controller: 'App\Controller\UserController::show'

user_edit:
    path: '/api/users/{id}/edit'
    controller: 'App\Controller\UserController::edit'

user_delete:
    path: '/api/users/{id}/delete'
    controller: 'App\Controller\UserController::delete'

birthday_create:
    path: '/birthday/new'
    controller: 'App\Controller\BirthdayController::create'

birthday_edit:
    path: '/birthday/{id}/edit'
    controller: 'App\Controller\BirthdayController::edit'

birthday_delete:
    path: '/birthday/{id}/delete'
    controller: 'App\Controller\BirthdayController::delete'
